CREATE DATABASE QL_TRUONG_HOC
--CHỌN CÂU LỆNH ĐỂ BÂM F5 ĐỂ TẠO --
--TÊN CƠ SỞ DỮ LIỆU,BẢNG, THUỘC TÍNH  KHÔNG ĐƯỢC TRÙNG--
--GỌI ĐẾN CƠ SỞ DỮ LIỆU ĐỂ LÀM VIỆC --
USE QL_TRUONG_HOC
--TẠO BẢNG SINH VIÊN--
--CÂU LỆNH TẠO BẢNG CREATER TABLE TÊN BẢNG--
CREATE TABLE SINH_VIEN
(
MASV CHAR(5) NOT NULL CONSTRAINT PK_SV PRIMARY KEY(MASV),
HO_TEN NVARCHAR(50) NOT NULL,
LOP NVARCHAR(30) NOT NULL,
CHUYEN_NGANH NVARCHAR(30) NOT NULL,
)
--THI THI LỆNH CHỌN CÂU LỆNH NHẤN F5--
--CÂU LỆNH ĐỂ TRUY VẤN ĐẾN BẢNG--
SELECT* FROM SINH_VIEN
--CÂU LỆNH ĐỂ CHÈN DỮ LIỆU VÀO BẢNG--
INSERT INTO SINH_VIEN(MASV,HO_TEN,LOP,CHUYEN_NGANH)
VALUES
('IT01',N'NGUYỄN NGỌC ANH ','K19.IT01','CNTT'),
('IT02',N'NGUYỄN THU HUYỀN','K19.IT02','CNTT'),
('IT03',N'HOÀNG MINH TRƯỜNG','K19.IT05','CNTT')

