
package PolyApp;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
public class MainForm extends javax.swing.JFrame {
        private StudentManagementPanel mStudentPanel;
        private GPAManagementPanel mGPAPanel;
    
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        //phóng to kích thước của cửa sổ mainhome 
        setExtendedState( JFrame.MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        tbrLogout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        Studentbutton = new javax.swing.JButton();
        Markbutton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        tbrAboutUs = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        mnuManageStudent = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuManageGPA = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuAboutUs = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        tbrLogout.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\logout-icon-32.png")); // NOI18N
        tbrLogout.setText("Đăng xuất");
        tbrLogout.setFocusable(false);
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogout);
        jToolBar1.add(jSeparator4);

        Studentbutton.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\10207-man-student-light-skin-tone-icon-32.png")); // NOI18N
        Studentbutton.setText("Quản lý sinh viên");
        Studentbutton.setFocusable(false);
        Studentbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Studentbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Studentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentbuttonActionPerformed(evt);
            }
        });
        jToolBar1.add(Studentbutton);

        Markbutton.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\gpa-icon-32.png")); // NOI18N
        Markbutton.setText("Quản lý điểm");
        Markbutton.setFocusable(false);
        Markbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Markbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Markbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkbuttonActionPerformed(evt);
            }
        });
        jToolBar1.add(Markbutton);
        jToolBar1.add(jSeparator5);

        tbrAboutUs.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\Actions-help-about-icon-32.png")); // NOI18N
        tbrAboutUs.setText("Trợ giúp");
        tbrAboutUs.setFocusable(false);
        tbrAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAboutUs);

        jMenu1.setText("Hệ thống");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\logout-icon-16.png")); // NOI18N
        jMenuItem5.setText("Đăng xuất ");
        jMenu1.add(jMenuItem5);

        mnu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnu.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\Button-Close-icon-16.png")); // NOI18N
        mnu.setText("Thoát");
        mnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuActionPerformed(evt);
            }
        });
        jMenu1.add(mnu);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý ");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mnuManageStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManageStudent.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\10207-man-student-light-skin-tone-icon-16.png")); // NOI18N
        mnuManageStudent.setText("Quản lý sinh viên ");
        mnuManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageStudentActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageStudent);
        jMenu2.add(jSeparator2);

        mnuManageGPA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManageGPA.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\gpa-icon.png")); // NOI18N
        mnuManageGPA.setText("Quản lý điểm");
        mnuManageGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageGPAActionPerformed(evt);
            }
        });
        jMenu2.add(mnuManageGPA);

        jMenuBar1.add(jMenu2);

        jMenu3.setText(" Trợ giúp");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem10.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\Actions-help-about-icon-16.png")); // NOI18N
        jMenuItem10.setText("Nội dung ");
        jMenu3.add(jMenuItem10);
        jMenu3.add(jSeparator3);

        mnuAboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAboutUs.setIcon(new javax.swing.ImageIcon("E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\Help-icon-16.png")); // NOI18N
        mnuAboutUs.setText("Giới thiệu");
        mnuAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUsActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAboutUs);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplMainBoard)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageStudentActionPerformed
     if(mStudentPanel == null){
        mStudentPanel = new StudentManagementPanel();
       ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\10207-man-student-light-skin-tone-icon-16.png");
      tplMainBoard.addTab("Quản lý sinh viên", icon,mStudentPanel ,"Quản lý sinh viên" );
     }
       tplMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_mnuManageStudentActionPerformed

    private void mnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuActionPerformed
   //nút bấm nhanh trên màn hình giao diện chính 
    private void StudentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentbuttonActionPerformed
          if(mStudentPanel == null){
        mStudentPanel = new StudentManagementPanel();
       ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\10207-man-student-light-skin-tone-icon-16.png");
      tplMainBoard.addTab("Quản lý sinh viên", icon,mStudentPanel ,"Quản lý sinh viên" );
     }
       tplMainBoard.setSelectedComponent(mStudentPanel);
    }//GEN-LAST:event_StudentbuttonActionPerformed

    private void mnuManageGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageGPAActionPerformed
                if(mGPAPanel == null){
        mGPAPanel = new GPAManagementPanel();
       ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\gpa-icon.png");
      tplMainBoard.addTab("Quản lý điểm", icon,mGPAPanel ,"Quản lý điểm" );
     }
      tplMainBoard.setSelectedComponent(mGPAPanel);                                               

    }//GEN-LAST:event_mnuManageGPAActionPerformed
    //thuc hien xu ly phan gioi thieu này cần chú ý và tìm hiểu vì sao như vậy 
    private void tbrAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutUsActionPerformed
        AboutUsDialog aboutDialog = new AboutUsDialog(this,true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_tbrAboutUsActionPerformed
    //hàm gọi phần giới thiệu
    private void mnuAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUsActionPerformed
        tbrAboutUsActionPerformed(evt);
    }//GEN-LAST:event_mnuAboutUsActionPerformed

    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
        LoginDialog loginDialog = new LoginDialog(this,true);
        loginDialog.setVisible(true);
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Mở form đồng thời hai cái màn hình loginform và mainform
        //khai bao logindialog
        LoginDialog dialog = new LoginDialog(this,true);
        dialog.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void MarkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkbuttonActionPerformed
             if(mGPAPanel == null){
        mGPAPanel = new GPAManagementPanel();
       ImageIcon icon = new ImageIcon( "E:\\NetBeansProjects\\Poly-app\\src\\main\\resources\\Polyappicon\\gpa-icon.png");
      tplMainBoard.addTab("Quản lý điểm", icon,mGPAPanel ,"Quản lý điểm" );
     }
      tplMainBoard.setSelectedComponent(mGPAPanel);    
    }//GEN-LAST:event_MarkbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Markbutton;
    private javax.swing.JButton Studentbutton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnu;
    private javax.swing.JMenuItem mnuAboutUs;
    private javax.swing.JMenuItem mnuManageGPA;
    private javax.swing.JMenuItem mnuManageStudent;
    private javax.swing.JButton tbrAboutUs;
    private javax.swing.JButton tbrLogout;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
